server:
  port: 8181

#spring:
#  security:
#    user:
#      name: stluser
#      password: Sgh@123456
#      roles: ADMIN,USER
#security:
#  oauth2:
#    client:
#      client-id: microservice.io
#      client-secret: isuruk
#      access-token-validity-seconds: 300
#      authorized-grant-types: refresh_token,authorization_code,password,client_credentials
#      scope: READ,WRITE
#    authorization:
#      check-token-access: permitAll

